### ISSUE TITLE
Anyway to make a manual input for pegs?

### ISSUE THREAD

**Issue by ghost** [James-P-D/GeniusSquare#2]
I was wondering if there was anyway to make a manual input for the pegs so we can use the solver to actually solve the genius square. When I say manual input for pegs, I just mean like B4, F1,etc.

**Comment by James-P-D** [comment]
Hiya, @coolio79 , yes I think that wouldn't be too hard a change to make. Note however that the dice faces are cleverly designed so that all throws of the dice result in games that it is possible to solve.

For example, if you manually choose to put pegs at B1, B2, B5, B6, A2, and A5, then you create two single-cell 'holes' at two corners of the board. Since the game only comes with one 1x1 piece, the puzzle is impossible to solve.

**Comment by James-P-D** [comment]
Hi @coolio79 , I've updated the program so that it's possible to toggle the blocker pieces. Try updating and have a go.
